In [1]:
#import the libraries we want to use
import pandas as pd
import numpy as np

In [5]:
#load up our csv file into python
superheros = pd.read_csv("superhero_data.csv" , parse_dates = ["FIRST_YEAR"])

In [7]:
superheros.head()

,UNIVERSE,page_id,name,urlslug,ID,ALIGN,IS_AVENGER,AVENGER_STATUS,AVENGER_YEAR,EYES,...,SEX,SEXUALITY,ALIVE,APPEARANCES,FIRST_MONTH,FIRST_YEAR,DECEASED,RESURRECTED,Unnamed: 19,Unnamed: 20
0,DC,1702,Richard Occult (New Earth),Richard_Occult_(New_Earth),Secret Identity,ND,NO,ND,ND,Grey Eyes,...,Male Characters,Heterosexual Characters,Living Characters,125,October,1935,ND,ND,NaN,NaN
1,DC,158200,Arthur Pendragon (New Earth),Arthur_Pendragon_(New_Earth),Public Identity,Good Characters,NO,ND,ND,Brown Eyes,...,Male Characters,Heterosexual Characters,Living Characters,41,February,1936,ND,ND,NaN,NaN
2,DC,289378,Bedivere (New Earth),Bedivere_(New_Earth),ND,ND,NO,ND,ND,ND,...,Male Characters,Heterosexual Characters,Living Characters,ND,February,1936,ND,ND,NaN,NaN
3,DC,11333,Franklin Delano Roosevelt (New Earth),Franklin_Delano_Roosevelt_(New_Earth),Public Identity,Good Characters,NO,ND,ND,ND,...,Male Characters,Heterosexual Characters,Living Characters,52,March,1936,ND,ND,NaN,NaN
4,DC,342641,Gareth (New Earth),Gareth_(New_Earth),ND,ND,NO,ND,ND,ND,...,Male Characters,Heterosexual Characters,Living Characters,1,February,1936,ND,ND,NaN,NaN

In [9]:
#introduction of the dataframe. From Pandas (pd) library
df = pd.DataFrame(data = superheros)
print(df)

      UNIVERSE page_id                                   name  \
0           DC    1702             Richard Occult (New Earth)
1           DC  158200           Arthur Pendragon (New Earth)
2           DC  289378                   Bedivere (New Earth)
3           DC   11333  Franklin Delano Roosevelt (New Earth)
4           DC  342641                     Gareth (New Earth)
...        ...     ...                                    ...
23415   MARVEL      ND                  Zola Hulk (Earth-616)
23416   MARVEL      ND              Zola Iron Man (Earth-616)
23417   MARVEL      ND                  Zola Thor (Earth-616)
23418   MARVEL      ND                    Zoltaro (Earth-616)
23419   MARVEL      ND                Zora Loftus (Earth-616)

                                     urlslug               ID  \
0                 Richard_Occult_(New_Earth)  Secret Identity
1               Arthur_Pendragon_(New_Earth)  Public Identity
2                       Bedivere_(New_Earth)               ND
3      Franklin_Delano_Roosevelt_(New_Earth)  Public Identity
4                         Gareth_(New_Earth)               ND
...                                      ...              ...
23415                  Zola_Hulk_(Earth-616)  Secret Identity
23416              Zola_Iron_Man_(Earth-616)  Secret Identity
23417                  Zola_Thor_(Earth-616)  Secret Identity
23418                    Zoltaro_(Earth-616)               ND
23419                Zora_Loftus_(Earth-616)  Secret Identity

                 ALIGN IS_AVENGER AVENGER_STATUS AVENGER_YEAR        EYES  \
0                   ND         NO             ND           ND   Grey Eyes
1      Good Characters         NO             ND           ND  Brown Eyes
2                   ND         NO             ND           ND          ND
3      Good Characters         NO             ND           ND          ND
4                   ND         NO             ND           ND          ND
...                ...        ...            ...          ...         ...
23415   Bad Characters         NO             ND           ND    Red Eyes
23416   Bad Characters         NO             ND           ND  Black Eyes
23417   Bad Characters         NO             ND           ND   Blue Eyes
23418   Bad Characters         NO             ND           ND          ND
23419   Bad Characters         NO             ND           ND          ND

       ...                SEX                SEXUALITY                ALIVE  \
0      ...    Male Characters  Heterosexual Characters    Living Characters
1      ...    Male Characters  Heterosexual Characters    Living Characters
2      ...    Male Characters  Heterosexual Characters    Living Characters
3      ...    Male Characters  Heterosexual Characters    Living Characters
4      ...    Male Characters  Heterosexual Characters    Living Characters
...    ...                ...                      ...                  ...
23415  ...    Male Characters  Heterosexual Characters    Living Characters
23416  ...    Male Characters  Heterosexual Characters    Living Characters
23417  ...    Male Characters  Heterosexual Characters    Living Characters
23418  ...    Male Characters  Heterosexual Characters  Deceased Characters
23419  ...  Female Characters  Heterosexual Characters    Living Characters

      APPEARANCES FIRST_MONTH FIRST_YEAR DECEASED RESURRECTED Unnamed: 19  \
0             125    October        1935       ND          ND         NaN
1              41   February        1936       ND          ND         NaN
2              ND   February        1936       ND          ND         NaN
3              52      March        1936       ND          ND         NaN
4               1   February        1936       ND          ND         NaN
...           ...         ...        ...      ...         ...         ...
23415           1          ND         ND       ND          ND         NaN
23416           1          ND         ND       ND          ND         NaN
23417           1          ND         ND       ND          ND         NaN
23418           2          ND         ND       ND          ND         NaN
23419          ND          ND         ND       ND          ND         NaN

       Unnamed: 20
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
23415          NaN
23416          NaN
23417          NaN
23418          NaN
23419          NaN

[23420 rows x 21 columns]

In [13]:
#What are different type of hair the superheros has?
pd.crosstab(superheros["HAIR"], superheros["ALIGN"])

ALIGN,Bad Characters,Good Characters,ND,Neutral Characters,Reformed Criminals
HAIR,,,,,
Auburn Hair,21,37,12,12,0
Bald,465,157,90,130,0
Bald formerly Brown Hair and sometimes Blond Hair,0,1,0,0,0
Black Hair,2205,1898,629,640,0
Black Hair (shaved bald),0,1,0,0,0
Black Hair (shaved),0,0,1,0,0
Black Hair shaved bald,0,1,0,0,0
Black Hair with White streaks,0,1,0,0,0
Blond Hair,719,1000,318,311,2
Blue Hair,44,25,12,17,0
Bronze Hair,0,1,0,0,0
Brown Hair,1257,1337,481,439,0
Brown Hair dyed Black,0,1,0,0,0
Brown Hair; No Hair,0,1,0,0,0
Brown or Green Hair,0,1,0,0,0
Dyed Hair,0,0,0,1,0
Gold Hair,3,7,1,2,0
Gray Hair dyed Black,0,1,0,0,0
Green Hair,68,55,21,16,0
Grey Hair,262,228,111,88,0
Light Brown Hair,0,5,0,1,0
Magenta Hair,2,2,1,0,0
ND,2991,1654,1305,588,0
No Hair,672,179,128,201,0
No Hair formerly Blond Hair,0,1,0,0,0
Orange Hair,13,25,11,16,0
Orange-brown Hair,3,0,0,0,0
Pink Hair,15,14,7,6,0
Platinum Blond Hair,1,0,0,1,0
Purple Hair,28,33,11,8,0
Red Hair,345,439,151,155,1
Red Hair formerly dyed Black,0,1,0,0,0
Reddish Blond Hair,3,3,0,0,0
Reddish Brown Hair,1,2,0,0,0
Silver Hair,5,8,4,4,0
Strawberry Blond,0,0,1,0,0
Strawberry Blond Hair,17,45,9,9,0
Variable,0,0,1,0,0
Variable Hair,15,6,3,8,0
Violet Hair,1,2,0,1,0
White Hair,450,406,126,121,0
Yellow Hair,9,4,3,4,0

In [24]:
#How many haroes have differnt type of hair and eyes?
bad_characters = pd.crosstab(index = superheros["HAIR"] == "Black Hair", columns = superheros["EYES"] == "Blue Eyes")

bad_characters.columns = ["Has blue eyes", "Does not have blue eyes"]
bad_characters.index = ["Has black hair", "Does not have black hair"]
bad_characters

                          Has blue eyes  Does not have blue eyes
Has black hair                    15577                     2471
Does not have black hair           4716                      656

In [17]:
#What are the different types of sexualityâ€™s of the characters? 
pd.crosstab(superheros["SEXUALITY"], superheros["ALIGN"], margins=True)

ALIGN,Bad Characters,Good Characters,ND,Neutral Characters,Reformed Criminals,All
SEXUALITY,,,,,,
Bisexual Characters,7,15,0,7,0,29
Genderfluid Characters,0,1,0,0,0,1
Heterosexual Characters,9590,7372,3402,2751,3,23118
Homosexual Characters,17,77,10,14,0,118
ND,2,117,24,6,0,149
Pansexual Characters,0,1,0,0,0,1
Transgender Characters,0,1,1,0,0,2
Transvestites,0,0,0,1,0,1
All,9616,7584,3437,2779,3,23419